### PR TITLE
Added Github link

### PR DESCRIPTION
**Pull request by EliTheCoder**
I added a link to the source code on the sidebar and the welcome screen. It should hopefully encourage development to the open source project. It needs to be tested to see if it looks good.

### CODE REVIEW

**Comment by EliTheCoder** [comment]
You might also want to change the button to say "Source" or "Source Code" instead. It's up to you.

**Comment by EliTheCoder** [comment]
image
image

**Comment by adenflorian** [comment]
LGTM! Thanks!

**Comment by adenflorian** [comment]
change is live in 0.8.20

**Pull request merged**
